# Generated by Django 5.0 on 2023-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_delete_userporfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default-avatar-icon-of-social-media-user-vector.jpeg', upload_to='profile_pictures/'),
        ),
    ]
